// MetroSim event schema.
//
// The version lives in the package name, metrosim.events.v1, so a v2 schema can
// sit alongside it. A removed field's number is reserved, never reused.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/events/events.proto

package eventspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Meta is stamped on every event so a downstream consumer can filter, join,
// or partition without parsing the payload-specific fields.
type Meta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       uint64                 `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`               // monotonic per-publisher; stable across retries
	Time          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`                                     // sim time at publish
	Scenario      string                 `protobuf:"bytes,3,opt,name=scenario,proto3" json:"scenario,omitempty"`                             // scenario name (e.g. "morning_rush")
	Policy        string                 `protobuf:"bytes,4,opt,name=policy,proto3" json:"policy,omitempty"`                                 // greedy, batch or region-sharded, plus "+reposition" if on
	Seed          int64                  `protobuf:"varint,5,opt,name=seed,proto3" json:"seed,omitempty"`                                    // scenario seed, for joining replicates
	PartitionKey  string                 `protobuf:"bytes,6,opt,name=partition_key,json=partitionKey,proto3" json:"partition_key,omitempty"` // Kafka partition key; MemoryBus ignores
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Meta) Reset() {
	*x = Meta{}
	mi := &file_proto_events_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Meta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Meta) ProtoMessage() {}

func (x *Meta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Meta.ProtoReflect.Descriptor instead.
func (*Meta) Descriptor() ([]byte, []int) {
	return file_proto_events_events_proto_rawDescGZIP(), []int{0}
}

func (x *Meta) GetEventId() uint64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *Meta) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *Meta) GetScenario() string {
	if x != nil {
		return x.Scenario
	}
	return ""
}

func (x *Meta) GetPolicy() string {
	if x != nil {
		return x.Policy
	}
	return ""
}

func (x *Meta) GetSeed() int64 {
	if x != nil {
		return x.Seed
	}
	return 0
}

func (x *Meta) GetPartitionKey() string {
	if x != nil {
		return x.PartitionKey
	}
	return ""
}

type TripRequested struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Meta            *Meta                  `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	RequestId       int64                  `protobuf:"varint,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	PickupNode      int64                  `protobuf:"varint,3,opt,name=pickup_node,json=pickupNode,proto3" json:"pickup_node,omitempty"`
	DestinationNode int64                  `protobuf:"varint,4,opt,name=destination_node,json=destinationNode,proto3" json:"destination_node,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TripRequested) Reset() {
	*x = TripRequested{}
	mi := &file_proto_events_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TripRequested) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TripRequested) ProtoMessage() {}

func (x *TripRequested) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TripRequested.ProtoReflect.Descriptor instead.
func (*TripRequested) Descriptor() ([]byte, []int) {
	return file_proto_events_events_proto_rawDescGZIP(), []int{1}
}

func (x *TripRequested) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *TripRequested) GetRequestId() int64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *TripRequested) GetPickupNode() int64 {
	if x != nil {
		return x.PickupNode
	}
	return 0
}

func (x *TripRequested) GetDestinationNode() int64 {
	if x != nil {
		return x.DestinationNode
	}
	return 0
}

type TripMatched struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Meta           *Meta                  `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	RideId         int64                  `protobuf:"varint,2,opt,name=ride_id,json=rideId,proto3" json:"ride_id,omitempty"`
	RequestId      int64                  `protobuf:"varint,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	DriverId       int64                  `protobuf:"varint,4,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	PickupNode     int64                  `protobuf:"varint,5,opt,name=pickup_node,json=pickupNode,proto3" json:"pickup_node,omitempty"`
	SurgeAtMatch   float64                `protobuf:"fixed64,6,opt,name=surge_at_match,json=surgeAtMatch,proto3" json:"surge_at_match,omitempty"`
	EtaCostSeconds float64                `protobuf:"fixed64,7,opt,name=eta_cost_seconds,json=etaCostSeconds,proto3" json:"eta_cost_seconds,omitempty"` // cost the policy minimized, in seconds
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TripMatched) Reset() {
	*x = TripMatched{}
	mi := &file_proto_events_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TripMatched) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TripMatched) ProtoMessage() {}

func (x *TripMatched) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TripMatched.ProtoReflect.Descriptor instead.
func (*TripMatched) Descriptor() ([]byte, []int) {
	return file_proto_events_events_proto_rawDescGZIP(), []int{2}
}

func (x *TripMatched) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *TripMatched) GetRideId() int64 {
	if x != nil {
		return x.RideId
	}
	return 0
}

func (x *TripMatched) GetRequestId() int64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *TripMatched) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *TripMatched) GetPickupNode() int64 {
	if x != nil {
		return x.PickupNode
	}
	return 0
}

func (x *TripMatched) GetSurgeAtMatch() float64 {
	if x != nil {
		return x.SurgeAtMatch
	}
	return 0
}

func (x *TripMatched) GetEtaCostSeconds() float64 {
	if x != nil {
		return x.EtaCostSeconds
	}
	return 0
}

type TripPickedUp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *Meta                  `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	RideId        int64                  `protobuf:"varint,2,opt,name=ride_id,json=rideId,proto3" json:"ride_id,omitempty"`
	DriverId      int64                  `protobuf:"varint,3,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TripPickedUp) Reset() {
	*x = TripPickedUp{}
	mi := &file_proto_events_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TripPickedUp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TripPickedUp) ProtoMessage() {}

func (x *TripPickedUp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TripPickedUp.ProtoReflect.Descriptor instead.
func (*TripPickedUp) Descriptor() ([]byte, []int) {
	return file_proto_events_events_proto_rawDescGZIP(), []int{3}
}

func (x *TripPickedUp) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *TripPickedUp) GetRideId() int64 {
	if x != nil {
		return x.RideId
	}
	return 0
}

func (x *TripPickedUp) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

type TripCompleted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *Meta                  `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	RideId        int64                  `protobuf:"varint,2,opt,name=ride_id,json=rideId,proto3" json:"ride_id,omitempty"`
	RequestId     int64                  `protobuf:"varint,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	DriverId      int64                  `protobuf:"varint,4,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	RequestTime   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=request_time,json=requestTime,proto3" json:"request_time,omitempty"`
	MatchTime     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=match_time,json=matchTime,proto3" json:"match_time,omitempty"`
	PickupTime    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=pickup_time,json=pickupTime,proto3" json:"pickup_time,omitempty"`
	DropoffTime   *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=dropoff_time,json=dropoffTime,proto3" json:"dropoff_time,omitempty"`
	PickupNode    int64                  `protobuf:"varint,9,opt,name=pickup_node,json=pickupNode,proto3" json:"pickup_node,omitempty"`
	DropoffNode   int64                  `protobuf:"varint,10,opt,name=dropoff_node,json=dropoffNode,proto3" json:"dropoff_node,omitempty"`
	PickupLat     float64                `protobuf:"fixed64,11,opt,name=pickup_lat,json=pickupLat,proto3" json:"pickup_lat,omitempty"`
	PickupLon     float64                `protobuf:"fixed64,12,opt,name=pickup_lon,json=pickupLon,proto3" json:"pickup_lon,omitempty"`
	DropoffLat    float64                `protobuf:"fixed64,13,opt,name=dropoff_lat,json=dropoffLat,proto3" json:"dropoff_lat,omitempty"`
	DropoffLon    float64                `protobuf:"fixed64,14,opt,name=dropoff_lon,json=dropoffLon,proto3" json:"dropoff_lon,omitempty"`
	SurgeAtMatch  float64                `protobuf:"fixed64,15,opt,name=surge_at_match,json=surgeAtMatch,proto3" json:"surge_at_match,omitempty"`
	EtaPredictedS float64                `protobuf:"fixed64,16,opt,name=eta_predicted_s,json=etaPredictedS,proto3" json:"eta_predicted_s,omitempty"` // model's trip-duration prediction at match time; 0 if no model loaded
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TripCompleted) Reset() {
	*x = TripCompleted{}
	mi := &file_proto_events_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TripCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TripCompleted) ProtoMessage() {}

func (x *TripCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TripCompleted.ProtoReflect.Descriptor instead.
func (*TripCompleted) Descriptor() ([]byte, []int) {
	return file_proto_events_events_proto_rawDescGZIP(), []int{4}
}

func (x *TripCompleted) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *TripCompleted) GetRideId() int64 {
	if x != nil {
		return x.RideId
	}
	return 0
}

func (x *TripCompleted) GetRequestId() int64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *TripCompleted) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *TripCompleted) GetRequestTime() *timestamppb.Timestamp {
	if x != nil {
		return x.RequestTime
	}
	return nil
}

func (x *TripCompleted) GetMatchTime() *timestamppb.Timestamp {
	if x != nil {
		return x.MatchTime
	}
	return nil
}

func (x *TripCompleted) GetPickupTime() *timestamppb.Timestamp {
	if x != nil {
		return x.PickupTime
	}
	return nil
}

func (x *TripCompleted) GetDropoffTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DropoffTime
	}
	return nil
}

func (x *TripCompleted) GetPickupNode() int64 {
	if x != nil {
		return x.PickupNode
	}
	return 0
}

func (x *TripCompleted) GetDropoffNode() int64 {
	if x != nil {
		return x.DropoffNode
	}
	return 0
}

func (x *TripCompleted) GetPickupLat() float64 {
	if x != nil {
		return x.PickupLat
	}
	return 0
}

func (x *TripCompleted) GetPickupLon() float64 {
	if x != nil {
		return x.PickupLon
	}
	return 0
}

func (x *TripCompleted) GetDropoffLat() float64 {
	if x != nil {
		return x.DropoffLat
	}
	return 0
}

func (x *TripCompleted) GetDropoffLon() float64 {
	if x != nil {
		return x.DropoffLon
	}
	return 0
}

func (x *TripCompleted) GetSurgeAtMatch() float64 {
	if x != nil {
		return x.SurgeAtMatch
	}
	return 0
}

func (x *TripCompleted) GetEtaPredictedS() float64 {
	if x != nil {
		return x.EtaPredictedS
	}
	return 0
}

// A rider gave up on a request left unmatched past --max-wait.
type TripAbandoned struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *Meta                  `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	RequestId     int64                  `protobuf:"varint,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	PickupNode    int64                  `protobuf:"varint,3,opt,name=pickup_node,json=pickupNode,proto3" json:"pickup_node,omitempty"`
	WaitedS       float64                `protobuf:"fixed64,4,opt,name=waited_s,json=waitedS,proto3" json:"waited_s,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TripAbandoned) Reset() {
	*x = TripAbandoned{}
	mi := &file_proto_events_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TripAbandoned) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TripAbandoned) ProtoMessage() {}

func (x *TripAbandoned) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TripAbandoned.ProtoReflect.Descriptor instead.
func (*TripAbandoned) Descriptor() ([]byte, []int) {
	return file_proto_events_events_proto_rawDescGZIP(), []int{5}
}

func (x *TripAbandoned) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *TripAbandoned) GetRequestId() int64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *TripAbandoned) GetPickupNode() int64 {
	if x != nil {
		return x.PickupNode
	}
	return 0
}

func (x *TripAbandoned) GetWaitedS() float64 {
	if x != nil {
		return x.WaitedS
	}
	return 0
}

// A driver dropped a ride before pickup. The request goes back in the queue
// and can be matched again under a new ride_id.
type TripCancelled struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *Meta                  `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	RideId        int64                  `protobuf:"varint,2,opt,name=ride_id,json=rideId,proto3" json:"ride_id,omitempty"`
	RequestId     int64                  `protobuf:"varint,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	DriverId      int64                  `protobuf:"varint,4,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TripCancelled) Reset() {
	*x = TripCancelled{}
	mi := &file_proto_events_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TripCancelled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TripCancelled) ProtoMessage() {}

func (x *TripCancelled) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TripCancelled.ProtoReflect.Descriptor instead.
func (*TripCancelled) Descriptor() ([]byte, []int) {
	return file_proto_events_events_proto_rawDescGZIP(), []int{6}
}

func (x *TripCancelled) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *TripCancelled) GetRideId() int64 {
	if x != nil {
		return x.RideId
	}
	return 0
}

func (x *TripCancelled) GetRequestId() int64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *TripCancelled) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

type DriverLocationUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *Meta                  `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	DriverId      int64                  `protobuf:"varint,2,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Lat           float64                `protobuf:"fixed64,3,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float64                `protobuf:"fixed64,4,opt,name=lon,proto3" json:"lon,omitempty"`
	State         string                 `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"` // idle, repositioning, enroute, or assigned when heading to a pickup
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverLocationUpdate) Reset() {
	*x = DriverLocationUpdate{}
	mi := &file_proto_events_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverLocationUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverLocationUpdate) ProtoMessage() {}

func (x *DriverLocationUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverLocationUpdate.ProtoReflect.Descriptor instead.
func (*DriverLocationUpdate) Descriptor() ([]byte, []int) {
	return file_proto_events_events_proto_rawDescGZIP(), []int{7}
}

func (x *DriverLocationUpdate) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *DriverLocationUpdate) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *DriverLocationUpdate) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *DriverLocationUpdate) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *DriverLocationUpdate) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type SurgeUpdated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *Meta                  `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	H3Cell        string                 `protobuf:"bytes,2,opt,name=h3_cell,json=h3Cell,proto3" json:"h3_cell,omitempty"` // H3 cell hex string at the surge resolution
	Multiplier    float64                `protobuf:"fixed64,3,opt,name=multiplier,proto3" json:"multiplier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SurgeUpdated) Reset() {
	*x = SurgeUpdated{}
	mi := &file_proto_events_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SurgeUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SurgeUpdated) ProtoMessage() {}

func (x *SurgeUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SurgeUpdated.ProtoReflect.Descriptor instead.
func (*SurgeUpdated) Descriptor() ([]byte, []int) {
	return file_proto_events_events_proto_rawDescGZIP(), []int{8}
}

func (x *SurgeUpdated) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *SurgeUpdated) GetH3Cell() string {
	if x != nil {
		return x.H3Cell
	}
	return ""
}

func (x *SurgeUpdated) GetMultiplier() float64 {
	if x != nil {
		return x.Multiplier
	}
	return 0
}

var File_proto_events_events_proto protoreflect.FileDescriptor

const file_proto_events_events_proto_rawDesc = "" +
	"\n" +
	"\x19proto/events/events.proto\x12\x12metrosim.events.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbe\x01\n" +
	"\x04Meta\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\x04R\aeventId\x12.\n" +
	"\x04time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x1a\n" +
	"\bscenario\x18\x03 \x01(\tR\bscenario\x12\x16\n" +
	"\x06policy\x18\x04 \x01(\tR\x06policy\x12\x12\n" +
	"\x04seed\x18\x05 \x01(\x03R\x04seed\x12#\n" +
	"\rpartition_key\x18\x06 \x01(\tR\fpartitionKey\"\xa8\x01\n" +
	"\rTripRequested\x12,\n" +
	"\x04meta\x18\x01 \x01(\v2\x18.metrosim.events.v1.MetaR\x04meta\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\x03R\trequestId\x12\x1f\n" +
	"\vpickup_node\x18\x03 \x01(\x03R\n" +
	"pickupNode\x12)\n" +
	"\x10destination_node\x18\x04 \x01(\x03R\x0fdestinationNode\"\x81\x02\n" +
	"\vTripMatched\x12,\n" +
	"\x04meta\x18\x01 \x01(\v2\x18.metrosim.events.v1.MetaR\x04meta\x12\x17\n" +
	"\aride_id\x18\x02 \x01(\x03R\x06rideId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\x03R\trequestId\x12\x1b\n" +
	"\tdriver_id\x18\x04 \x01(\x03R\bdriverId\x12\x1f\n" +
	"\vpickup_node\x18\x05 \x01(\x03R\n" +
	"pickupNode\x12$\n" +
	"\x0esurge_at_match\x18\x06 \x01(\x01R\fsurgeAtMatch\x12(\n" +
	"\x10eta_cost_seconds\x18\a \x01(\x01R\x0eetaCostSeconds\"r\n" +
	"\fTripPickedUp\x12,\n" +
	"\x04meta\x18\x01 \x01(\v2\x18.metrosim.events.v1.MetaR\x04meta\x12\x17\n" +
	"\aride_id\x18\x02 \x01(\x03R\x06rideId\x12\x1b\n" +
	"\tdriver_id\x18\x03 \x01(\x03R\bdriverId\"\x9a\x05\n" +
	"\rTripCompleted\x12,\n" +
	"\x04meta\x18\x01 \x01(\v2\x18.metrosim.events.v1.MetaR\x04meta\x12\x17\n" +
	"\aride_id\x18\x02 \x01(\x03R\x06rideId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\x03R\trequestId\x12\x1b\n" +
	"\tdriver_id\x18\x04 \x01(\x03R\bdriverId\x12=\n" +
	"\frequest_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vrequestTime\x129\n" +
	"\n" +
	"match_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tmatchTime\x12;\n" +
	"\vpickup_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"pickupTime\x12=\n" +
	"\fdropoff_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vdropoffTime\x12\x1f\n" +
	"\vpickup_node\x18\t \x01(\x03R\n" +
	"pickupNode\x12!\n" +
	"\fdropoff_node\x18\n" +
	" \x01(\x03R\vdropoffNode\x12\x1d\n" +
	"\n" +
	"pickup_lat\x18\v \x01(\x01R\tpickupLat\x12\x1d\n" +
	"\n" +
	"pickup_lon\x18\f \x01(\x01R\tpickupLon\x12\x1f\n" +
	"\vdropoff_lat\x18\r \x01(\x01R\n" +
	"dropoffLat\x12\x1f\n" +
	"\vdropoff_lon\x18\x0e \x01(\x01R\n" +
	"dropoffLon\x12$\n" +
	"\x0esurge_at_match\x18\x0f \x01(\x01R\fsurgeAtMatch\x12&\n" +
	"\x0feta_predicted_s\x18\x10 \x01(\x01R\retaPredictedS\"\x98\x01\n" +
	"\rTripAbandoned\x12,\n" +
	"\x04meta\x18\x01 \x01(\v2\x18.metrosim.events.v1.MetaR\x04meta\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\x03R\trequestId\x12\x1f\n" +
	"\vpickup_node\x18\x03 \x01(\x03R\n" +
	"pickupNode\x12\x19\n" +
	"\bwaited_s\x18\x04 \x01(\x01R\awaitedS\"\x92\x01\n" +
	"\rTripCancelled\x12,\n" +
	"\x04meta\x18\x01 \x01(\v2\x18.metrosim.events.v1.MetaR\x04meta\x12\x17\n" +
	"\aride_id\x18\x02 \x01(\x03R\x06rideId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\x03R\trequestId\x12\x1b\n" +
	"\tdriver_id\x18\x04 \x01(\x03R\bdriverId\"\x9b\x01\n" +
	"\x14DriverLocationUpdate\x12,\n" +
	"\x04meta\x18\x01 \x01(\v2\x18.metrosim.events.v1.MetaR\x04meta\x12\x1b\n" +
	"\tdriver_id\x18\x02 \x01(\x03R\bdriverId\x12\x10\n" +
	"\x03lat\x18\x03 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x04 \x01(\x01R\x03lon\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\"u\n" +
	"\fSurgeUpdated\x12,\n" +
	"\x04meta\x18\x01 \x01(\v2\x18.metrosim.events.v1.MetaR\x04meta\x12\x17\n" +
	"\ah3_cell\x18\x02 \x01(\tR\x06h3Cell\x12\x1e\n" +
	"\n" +
	"multiplier\x18\x03 \x01(\x01R\n" +
	"multiplierB9Z7github.com/Deathslayer89/MetroSim/proto/events;eventspbb\x06proto3"

var (
	file_proto_events_events_proto_rawDescOnce sync.Once
	file_proto_events_events_proto_rawDescData []byte
)

func file_proto_events_events_proto_rawDescGZIP() []byte {
	file_proto_events_events_proto_rawDescOnce.Do(func() {
		file_proto_events_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_events_events_proto_rawDesc), len(file_proto_events_events_proto_rawDesc)))
	})
	return file_proto_events_events_proto_rawDescData
}

var file_proto_events_events_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_events_events_proto_goTypes = []any{
	(*Meta)(nil),                  // 0: metrosim.events.v1.Meta
	(*TripRequested)(nil),         // 1: metrosim.events.v1.TripRequested
	(*TripMatched)(nil),           // 2: metrosim.events.v1.TripMatched
	(*TripPickedUp)(nil),          // 3: metrosim.events.v1.TripPickedUp
	(*TripCompleted)(nil),         // 4: metrosim.events.v1.TripCompleted
	(*TripAbandoned)(nil),         // 5: metrosim.events.v1.TripAbandoned
	(*TripCancelled)(nil),         // 6: metrosim.events.v1.TripCancelled
	(*DriverLocationUpdate)(nil),  // 7: metrosim.events.v1.DriverLocationUpdate
	(*SurgeUpdated)(nil),          // 8: metrosim.events.v1.SurgeUpdated
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_proto_events_events_proto_depIdxs = []int32{
	9,  // 0: metrosim.events.v1.Meta.time:type_name -> google.protobuf.Timestamp
	0,  // 1: metrosim.events.v1.TripRequested.meta:type_name -> metrosim.events.v1.Meta
	0,  // 2: metrosim.events.v1.TripMatched.meta:type_name -> metrosim.events.v1.Meta
	0,  // 3: metrosim.events.v1.TripPickedUp.meta:type_name -> metrosim.events.v1.Meta
	0,  // 4: metrosim.events.v1.TripCompleted.meta:type_name -> metrosim.events.v1.Meta
	9,  // 5: metrosim.events.v1.TripCompleted.request_time:type_name -> google.protobuf.Timestamp
	9,  // 6: metrosim.events.v1.TripCompleted.match_time:type_name -> google.protobuf.Timestamp
	9,  // 7: metrosim.events.v1.TripCompleted.pickup_time:type_name -> google.protobuf.Timestamp
	9,  // 8: metrosim.events.v1.TripCompleted.dropoff_time:type_name -> google.protobuf.Timestamp
	0,  // 9: metrosim.events.v1.TripAbandoned.meta:type_name -> metrosim.events.v1.Meta
	0,  // 10: metrosim.events.v1.TripCancelled.meta:type_name -> metrosim.events.v1.Meta
	0,  // 11: metrosim.events.v1.DriverLocationUpdate.meta:type_name -> metrosim.events.v1.Meta
	0,  // 12: metrosim.events.v1.SurgeUpdated.meta:type_name -> metrosim.events.v1.Meta
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_proto_events_events_proto_init() }
func file_proto_events_events_proto_init() {
	if File_proto_events_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_events_events_proto_rawDesc), len(file_proto_events_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_events_events_proto_goTypes,
		DependencyIndexes: file_proto_events_events_proto_depIdxs,
		MessageInfos:      file_proto_events_events_proto_msgTypes,
	}.Build()
	File_proto_events_events_proto = out.File
	file_proto_events_events_proto_goTypes = nil
	file_proto_events_events_proto_depIdxs = nil
}
